[package]
name = "bamtools"
kind = "tool"
version = "2.5.3"
release = 1
license = "Apache-2.0"
main = "src/main.taf"

[repository]
url = "https://github.com/taffish/bamtools"

[command]
name = "taf-bamtools"

[runtime]
pipe = true
command_mode = true

[container]
image = "ghcr.io/taffish/bamtools:2.5.3-r1"
dockerfile = "docker/Dockerfile"
build_platforms = "linux/amd64,linux/arm64"

[upstream]
type = "github"
repo = "pezmaster31/bamtools"
watch = "tags"
strip_prefix = "v"

[smoke]
backend = "docker"
timeout = 60
exist = ["bamtools"]
test = ["bamtools --help", "bamtools --version 2>&1 | grep -F 'bamtools 2.5.3' >/dev/null"]
